homepage:
    pattern:  /
    defaults: { _controller: AppFrontendBundle:Homepage:index }


cart_put:
    pattern:  /cart/put
    defaults: { _controller: AppFrontendBundle:Cart:put }

cart_remove:
    pattern:  /cart/remove
    defaults: { _controller: AppFrontendBundle:Cart:remove }

cart_clear:
    pattern:  /cart/clear
    defaults: { _controller: AppFrontendBundle:Cart:clear }